# D:\Games\FTB\scripts\ships\Hardpoints\FTB_Virulent.py
# This file was automatically generated - modify at your own risk.
#

import App
import GlobalPropertyTemplates
# Setting up local templates.
#################################################
PortImpulse = App.EngineProperty_Create("Port Impulse")
PortImpulse.SetMaxCondition(1245.0)
PortImpulse.SetCritical(0)
PortImpulse.SetTargetable(1)
PortImpulse.SetPrimary(1)
PortImpulse.SetPosition(-0.097824, -0.199282, -0.049071)
PortImpulse.SetPosition2D(41.0669010989, 67.4457153829)
PortImpulse.SetRepairComplexity(3.0)
PortImpulse.SetDisabledPercentage(0.5)
PortImpulse.SetRadius(0.009000)
PortImpulse.SetEngineType(PortImpulse.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(PortImpulse)
#################################################
PortWarp = App.EngineProperty_Create("Port Warp")
PortWarp.SetMaxCondition(1960.0)
PortWarp.SetCritical(0)
PortWarp.SetTargetable(1)
PortWarp.SetPrimary(1)
PortWarp.SetPosition(-0.545000, 0.121620, -0.054753)
PortWarp.SetPosition2D(-63.7655677656, 62.6293119478)
PortWarp.SetRepairComplexity(3.0)
PortWarp.SetDisabledPercentage(0.5)
PortWarp.SetRadius(0.400000)
PortWarp.SetEngineType(PortWarp.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(PortWarp)
#################################################
StarWarp = App.EngineProperty_Create("Star Warp")
StarWarp.SetMaxCondition(1960.0)
StarWarp.SetCritical(0)
StarWarp.SetTargetable(1)
StarWarp.SetPrimary(1)
StarWarp.SetPosition(0.545000, 0.121620, -0.054753)
StarWarp.SetPosition2D(191.765567766, 62.6293119478)
StarWarp.SetRepairComplexity(3.0)
StarWarp.SetDisabledPercentage(0.5)
StarWarp.SetRadius(0.400000)
StarWarp.SetEngineType(StarWarp.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(StarWarp)
#################################################
ProbeLauncher = App.ObjectEmitterProperty_Create("Probe Launcher")

ProbeLauncherForward = App.TGPoint3()
ProbeLauncherForward.SetXYZ(0.000000, 1.000000, 0.000000)
ProbeLauncherUp = App.TGPoint3()
ProbeLauncherUp.SetXYZ(0.000000, 0.000000, 1.000000)
ProbeLauncherRight = App.TGPoint3()
ProbeLauncherRight.SetXYZ(1.000000, 0.000000, 0.000000)
ProbeLauncher.SetOrientation(ProbeLauncherForward, ProbeLauncherUp, ProbeLauncherRight)
ProbeLauncherPosition = App.TGPoint3()
ProbeLauncherPosition.SetXYZ(0.000000, 0.484600, 0.004191)
ProbeLauncher.SetPosition(ProbeLauncherPosition)
ProbeLauncher.SetEmittedObjectType(ProbeLauncher.OEP_PROBE)
App.g_kModelPropertyManager.RegisterLocalTemplate(ProbeLauncher)
#################################################
ImpulseEngines = App.ImpulseEngineProperty_Create("Impulse Engines")
ImpulseEngines.SetMaxCondition(1236.0)
ImpulseEngines.SetCritical(0)
ImpulseEngines.SetTargetable(0)
ImpulseEngines.SetPrimary(1)
ImpulseEngines.SetPosition(0.000000, 0.000000, 0.000000)
ImpulseEngines.SetPosition2D(64.0, 64.0)
ImpulseEngines.SetRepairComplexity(3.0)
ImpulseEngines.SetDisabledPercentage(0.5)
ImpulseEngines.SetRadius(0.003000)
ImpulseEngines.SetNormalPowerPerSecond(2287.31707317)
ImpulseEngines.SetMaxAccel(7.425)
ImpulseEngines.SetMaxAngularAccel(0.225)
ImpulseEngines.SetMaxAngularVelocity(0.375)
ImpulseEngines.SetMaxSpeed(12.78125)
ImpulseEngines.SetEngineSound('Federation Engines')
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngines)
#################################################
StarBeam = App.PhaserProperty_Create("Star Beam")
StarBeam.SetMaxCondition(1235.0)
StarBeam.SetCritical(0)
StarBeam.SetTargetable(1)
StarBeam.SetPrimary(1)
StarBeam.SetPosition(0.102973, 0.060300, 0.081145)
StarBeam.SetPosition2D(88.1401904762, 66.8559259788)
StarBeam.SetRepairComplexity(4.0)
StarBeam.SetDisabledPercentage(0.75)
StarBeam.SetRadius(0.002000)
StarBeam.SetDumbfire(0)
StarBeam.SetWeaponID(1)
StarBeam.SetGroups(1)
StarBeam.SetDamageRadiusFactor(0.100000)
StarBeam.SetIconNum(364)
StarBeam.SetIconPositionX(76)
StarBeam.SetIconPositionY(36)
StarBeam.SetIconAboveShip(1)
StarBeam.SetFireSound('FTB Polaron Beam')
StarBeam.SetMaxCharge(1.5)
StarBeam.SetMaxDamage(3600.0)
StarBeam.SetMaxDamageDistance(45.0)
StarBeam.SetMinFiringCharge(1.0)
StarBeam.SetNormalDischargeRate(0.255)
StarBeam.SetRechargeRate(0.013)
StarBeam.SetIndicatorIconNum(510)
StarBeam.SetIndicatorIconPositionX(69)
StarBeam.SetIndicatorIconPositionY(46)
StarBeamForward = App.TGPoint3()
StarBeamForward.SetXYZ(0.759965, 0.000000, 0.649964)
StarBeamUp = App.TGPoint3()
StarBeamUp.SetXYZ(-0.468923, 0.000000, 0.883239)
StarBeam.SetOrientation(StarBeamForward, StarBeamUp)
StarBeam.SetWidth(0.001000)
StarBeam.SetLength(0.001000)
StarBeam.SetArcWidthAngles(-0.959931, 1.308997)
StarBeam.SetArcHeightAngles(-0.959931, 0.785398)
StarBeam.SetPhaserTextureStart(16)
StarBeam.SetPhaserTextureEnd(23)
StarBeam.SetPhaserWidth(0.3)
StarBeam.SetNumSides(6)
StarBeam.SetMainRadius(0.075)
StarBeam.SetTaperRadius(0.03)
StarBeam.SetCoreScale(0.175)
StarBeam.SetTaperRatio(0.25)
StarBeam.SetTaperMinLength(5.0)
StarBeam.SetTaperMaxLength(30.0)
StarBeam.SetLengthTextureTilePerUnit(0.05)
StarBeam.SetPerimeterTile(1.0)
StarBeam.SetTextureSpeed(2.5)
StarBeam.SetTextureName('Custom/FTB/textures/Tactical/Laurelin_poleron01.tga')
kColor = App.TGColorA()
kColor.SetRGBA(0.000000, 0.000000, 0.627451, 1.000000)
StarBeam.SetOuterShellColor(kColor)
kColor.SetRGBA(0.003922, 0.619608, 0.992157, 0.803922)
StarBeam.SetInnerShellColor(kColor)
kColor.SetRGBA(0.231373, 0.254902, 0.513726, 1.000000)
StarBeam.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.000000, 1.000000, 1.000000, 1.000000)
StarBeam.SetInnerCoreColor(kColor)
App.g_kModelPropertyManager.RegisterLocalTemplate(StarBeam)
#################################################
PortBeam = App.PhaserProperty_Create("Port Beam")
PortBeam.SetMaxCondition(1235.0)
PortBeam.SetCritical(0)
PortBeam.SetTargetable(1)
PortBeam.SetPrimary(1)
PortBeam.SetPosition(-0.102973, 0.060300, 0.081145)
PortBeam.SetPosition2D(39.8598095238, 66.8559259788)
PortBeam.SetRepairComplexity(4.0)
PortBeam.SetDisabledPercentage(0.75)
PortBeam.SetRadius(0.002000)
PortBeam.SetDumbfire(0)
PortBeam.SetWeaponID(1)
PortBeam.SetGroups(1)
PortBeam.SetDamageRadiusFactor(0.100000)
PortBeam.SetIconNum(364)
PortBeam.SetIconPositionX(55)
PortBeam.SetIconPositionY(36)
PortBeam.SetIconAboveShip(1)
PortBeam.SetFireSound('FTB Polaron Beam')
PortBeam.SetMaxCharge(1.5)
PortBeam.SetMaxDamage(3600.0)
PortBeam.SetMaxDamageDistance(45.0)
PortBeam.SetMinFiringCharge(1.0)
PortBeam.SetNormalDischargeRate(0.255)
PortBeam.SetRechargeRate(0.013)
PortBeam.SetIndicatorIconNum(510)
PortBeam.SetIndicatorIconPositionX(48)
PortBeam.SetIndicatorIconPositionY(46)
PortBeamForward = App.TGPoint3()
PortBeamForward.SetXYZ(-0.759965, 0.000000, 0.649964)
PortBeamUp = App.TGPoint3()
PortBeamUp.SetXYZ(0.468923, 0.000000, 0.883239)
PortBeam.SetOrientation(PortBeamForward, PortBeamUp)
PortBeam.SetWidth(0.001000)
PortBeam.SetLength(0.001000)
PortBeam.SetArcWidthAngles(-1.308997, 0.959931)
PortBeam.SetArcHeightAngles(-0.959931, 0.785398)
PortBeam.SetPhaserTextureStart(16)
PortBeam.SetPhaserTextureEnd(23)
PortBeam.SetPhaserWidth(0.3)
PortBeam.SetNumSides(6)
PortBeam.SetMainRadius(0.075)
PortBeam.SetTaperRadius(0.03)
PortBeam.SetCoreScale(0.175)
PortBeam.SetTaperRatio(0.25)
PortBeam.SetTaperMinLength(5.0)
PortBeam.SetTaperMaxLength(30.0)
PortBeam.SetLengthTextureTilePerUnit(0.05)
PortBeam.SetPerimeterTile(1.0)
PortBeam.SetTextureSpeed(2.5)
PortBeam.SetTextureName('Custom/FTB/textures/Tactical/Laurelin_poleron01.tga')
kColor = App.TGColorA()
kColor.SetRGBA(0.000000, 0.000000, 0.627451, 1.000000)
PortBeam.SetOuterShellColor(kColor)
kColor.SetRGBA(0.003922, 0.619608, 0.992157, 0.803922)
PortBeam.SetInnerShellColor(kColor)
kColor.SetRGBA(0.231373, 0.254902, 0.513726, 1.000000)
PortBeam.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.000000, 1.000000, 1.000000, 1.000000)
PortBeam.SetInnerCoreColor(kColor)
App.g_kModelPropertyManager.RegisterLocalTemplate(PortBeam)
# Property load function.
MineLauncher = App.PulseWeaponProperty_Create("Mine Launcher")
MineLauncher.SetMaxCondition(1428.0)
MineLauncher.SetCritical(0)
MineLauncher.SetTargetable(1)
MineLauncher.SetPrimary(1)
MineLauncher.SetPosition(0.000000, -0.321321, 0.177212)
MineLauncher.SetPosition2D(64.0, 53.492905948)
MineLauncher.SetRepairComplexity(4.0)
MineLauncher.SetDisabledPercentage(0.75)
MineLauncher.SetRadius(0.125000)
MineLauncher.SetDumbfire(1)
MineLauncher.SetWeaponID(0)
MineLauncher.SetGroups(0)
MineLauncher.SetDamageRadiusFactor(0.12)
MineLauncher.SetIconNum(365)
MineLauncher.SetIconPositionX(77)
MineLauncher.SetIconPositionY(98)
MineLauncher.SetIconAboveShip(1)
MineLauncher.SetFireSound('FTB Klingon Pulse')
MineLauncher.SetMaxCharge(4.0)
MineLauncher.SetMaxDamage(5000.0)
MineLauncher.SetMaxDamageDistance(200.0)
MineLauncher.SetMinFiringCharge(1.0)
MineLauncher.SetNormalDischargeRate(1.0)
MineLauncher.SetRechargeRate(0.036)
MineLauncher.SetIndicatorIconNum(513)
MineLauncher.SetIndicatorIconPositionX(59)
MineLauncher.SetIndicatorIconPositionY(95)
MineLauncherForward = App.TGPoint3()
MineLauncherForward.SetXYZ(0.000000, -0.300996, 0.953625)
MineLauncherUp = App.TGPoint3()
MineLauncherUp.SetXYZ(0.000000, 0.997676, 0.068134)
MineLauncher.SetOrientation(MineLauncherForward, MineLauncherUp)
MineLauncher.SetArcWidthAngles(-1.396263, 1.396263)
MineLauncher.SetArcHeightAngles(-0.698132, 1.570796)
MineLauncher.SetCooldownTime(4.0)
MineLauncher.SetModuleName('ftb.Projectiles.FTBDomMine')
App.g_kModelPropertyManager.RegisterLocalTemplate(MineLauncher)
#################################################
ShieldGenerator = App.ShieldProperty_Create("Shield Generator")
ShieldGenerator.SetMaxCondition(1261.0)
ShieldGenerator.SetCritical(0)
ShieldGenerator.SetTargetable(1)
ShieldGenerator.SetPrimary(1)
ShieldGenerator.SetPosition(0.000000, -0.331148, 0.170150)
ShieldGenerator.SetPosition2D(64.0, 53.1562719414)
ShieldGenerator.SetRepairComplexity(2.0)
ShieldGenerator.SetDisabledPercentage(0.5)
ShieldGenerator.SetRadius(0.020000)
ShieldGenerator.SetNormalPowerPerSecond(425.0)
ShieldGeneratorShieldGlowColor = App.TGColorA()
ShieldGeneratorShieldGlowColor.SetRGBA(0.203922, 0.631373, 1.000000, 0.466667)
ShieldGenerator.SetShieldGlowColor(ShieldGeneratorShieldGlowColor)
ShieldGenerator.SetShieldGlowDecay(0.1)
ShieldGenerator.SetMaxShields(ShieldGenerator.FRONT_SHIELDS, 4250.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.REAR_SHIELDS, 2125.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.TOP_SHIELDS, 2125.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.BOTTOM_SHIELDS, 2125.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.LEFT_SHIELDS, 2125.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.RIGHT_SHIELDS, 2125.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.FRONT_SHIELDS, 4.01343570058)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.REAR_SHIELDS, 4.01343570058)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.TOP_SHIELDS, 4.01343570058)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.BOTTOM_SHIELDS, 4.01343570058)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.LEFT_SHIELDS, 4.01343570058)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.RIGHT_SHIELDS, 4.01343570058)
App.g_kModelPropertyManager.RegisterLocalTemplate(ShieldGenerator)
#################################################
WarpCore = App.PowerProperty_Create("Warp Core")
WarpCore.SetMaxCondition(1942.0)
WarpCore.SetCritical(1)
WarpCore.SetTargetable(1)
WarpCore.SetPrimary(1)
WarpCore.SetPosition(0.000000, -0.206598, 0.063274)
WarpCore.SetPosition2D(64.0, 60.9133802953)
WarpCore.SetRepairComplexity(2.0)
WarpCore.SetDisabledPercentage(0.5)
WarpCore.SetRadius(0.040000)
WarpCore.SetMainBatteryLimit(600000.0)
WarpCore.SetBackupBatteryLimit(192000.0)
WarpCore.SetMainConduitCapacity(2880.0)
WarpCore.SetBackupConduitCapacity(960.0)
WarpCore.SetPowerOutput(2400.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpCore)
#################################################
Hull = App.HullProperty_Create("Hull")
Hull.SetMaxCondition(6279.0)
Hull.SetCritical(1)
Hull.SetTargetable(1)
Hull.SetPrimary(1)
Hull.SetPosition(0.000000, -0.150000, 0.000000)
Hull.SetPosition2D(64.0, 64.0)
Hull.SetRepairComplexity(3.0)
Hull.SetDisabledPercentage(0.0)
Hull.SetRadius(0.800000)
App.g_kModelPropertyManager.RegisterLocalTemplate(Hull)
#################################################
ViewscreenForward = App.PositionOrientationProperty_Create("ViewscreenForward")

ViewscreenForwardForward = App.TGPoint3()
ViewscreenForwardForward.SetXYZ(0.000000, 1.000000, 0.000000)
ViewscreenForwardUp = App.TGPoint3()
ViewscreenForwardUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenForwardRight = App.TGPoint3()
ViewscreenForwardRight.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenForward.SetOrientation(ViewscreenForwardForward, ViewscreenForwardUp, ViewscreenForwardRight)
ViewscreenForwardPosition = App.TGPoint3()
ViewscreenForwardPosition.SetXYZ(0.000000, 0.091765, 0.120406)
ViewscreenForward.SetPosition(ViewscreenForwardPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenForward)
#################################################
ViewscreenBack = App.PositionOrientationProperty_Create("ViewscreenBack")

ViewscreenBackForward = App.TGPoint3()
ViewscreenBackForward.SetXYZ(0.000000, -1.000000, 0.000000)
ViewscreenBackUp = App.TGPoint3()
ViewscreenBackUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenBackRight = App.TGPoint3()
ViewscreenBackRight.SetXYZ(-1.000000, 0.000000, 0.000000)
ViewscreenBack.SetOrientation(ViewscreenBackForward, ViewscreenBackUp, ViewscreenBackRight)
ViewscreenBackPosition = App.TGPoint3()
ViewscreenBackPosition.SetXYZ(0.000000, -0.395456, 0.157094)
ViewscreenBack.SetPosition(ViewscreenBackPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenBack)
#################################################
ViewscreenLeft = App.PositionOrientationProperty_Create("ViewscreenLeft")

ViewscreenLeftForward = App.TGPoint3()
ViewscreenLeftForward.SetXYZ(-1.000000, 0.000000, 0.000000)
ViewscreenLeftUp = App.TGPoint3()
ViewscreenLeftUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenLeftRight = App.TGPoint3()
ViewscreenLeftRight.SetXYZ(0.000000, 1.000000, 0.000000)
ViewscreenLeft.SetOrientation(ViewscreenLeftForward, ViewscreenLeftUp, ViewscreenLeftRight)
ViewscreenLeftPosition = App.TGPoint3()
ViewscreenLeftPosition.SetXYZ(-0.022185, 0.193523, 0.183405)
ViewscreenLeft.SetPosition(ViewscreenLeftPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenLeft)
#################################################
ViewscreenRight = App.PositionOrientationProperty_Create("ViewscreenRight")

ViewscreenRightForward = App.TGPoint3()
ViewscreenRightForward.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenRightUp = App.TGPoint3()
ViewscreenRightUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenRightRight = App.TGPoint3()
ViewscreenRightRight.SetXYZ(0.000000, -1.000000, 0.000000)
ViewscreenRight.SetOrientation(ViewscreenRightForward, ViewscreenRightUp, ViewscreenRightRight)
ViewscreenRightPosition = App.TGPoint3()
ViewscreenRightPosition.SetXYZ(0.022185, 0.193523, 0.183405)
ViewscreenRight.SetPosition(ViewscreenRightPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenRight)
#################################################
ViewscreenUp = App.PositionOrientationProperty_Create("ViewscreenUp")

ViewscreenUpForward = App.TGPoint3()
ViewscreenUpForward.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenUpUp = App.TGPoint3()
ViewscreenUpUp.SetXYZ(0.000000, -1.000000, 0.000000)
ViewscreenUpRight = App.TGPoint3()
ViewscreenUpRight.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenUp.SetOrientation(ViewscreenUpForward, ViewscreenUpUp, ViewscreenUpRight)
ViewscreenUpPosition = App.TGPoint3()
ViewscreenUpPosition.SetXYZ(0.000000, 0.029840, 0.225446)
ViewscreenUp.SetPosition(ViewscreenUpPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenUp)
#################################################
ViewscreenDown = App.PositionOrientationProperty_Create("ViewscreenDown")

ViewscreenDownForward = App.TGPoint3()
ViewscreenDownForward.SetXYZ(0.000000, 0.000000, -1.000000)
ViewscreenDownUp = App.TGPoint3()
ViewscreenDownUp.SetXYZ(0.000000, 1.000000, 0.000000)
ViewscreenDownRight = App.TGPoint3()
ViewscreenDownRight.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenDown.SetOrientation(ViewscreenDownForward, ViewscreenDownUp, ViewscreenDownRight)
ViewscreenDownPosition = App.TGPoint3()
ViewscreenDownPosition.SetXYZ(0.000000, 0.158829, -0.026203)
ViewscreenDown.SetPosition(ViewscreenDownPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenDown)
#################################################
FirstPersonCamera = App.PositionOrientationProperty_Create("FirstPersonCamera")

FirstPersonCameraForward = App.TGPoint3()
FirstPersonCameraForward.SetXYZ(0.000000, 1.000000, 0.000000)
FirstPersonCameraUp = App.TGPoint3()
FirstPersonCameraUp.SetXYZ(0.000000, 0.000000, 1.000000)
FirstPersonCameraRight = App.TGPoint3()
FirstPersonCameraRight.SetXYZ(1.000000, 0.000000, 0.000000)
FirstPersonCamera.SetOrientation(FirstPersonCameraForward, FirstPersonCameraUp, FirstPersonCameraRight)
FirstPersonCameraPosition = App.TGPoint3()
FirstPersonCameraPosition.SetXYZ(0.000000, 0.495429, 0.022997)
FirstPersonCamera.SetPosition(FirstPersonCameraPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(FirstPersonCamera)
#################################################
MineReplicator = App.WeaponSystemProperty_Create("Mine Replicator")
MineReplicator.SetMaxCondition(1428.0)
MineReplicator.SetCritical(0)
MineReplicator.SetTargetable(0)
MineReplicator.SetPrimary(1)
MineReplicator.SetPosition(0.000000, 0.000000, 0.000000)
MineReplicator.SetPosition2D(64.0, 64.0)
MineReplicator.SetRepairComplexity(3.0)
MineReplicator.SetDisabledPercentage(0.5)
MineReplicator.SetRadius(0.125000)
MineReplicator.SetNormalPowerPerSecond(233.0)
MineReplicator.SetWeaponSystemType(MineReplicator.WST_PULSE)
MineReplicator.SetSingleFire(1)
MineReplicator.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
MineReplicator.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(MineReplicator)
#################################################
Phasers = App.WeaponSystemProperty_Create("Phasers")
Phasers.SetMaxCondition(1236.0)
Phasers.SetCritical(0)
Phasers.SetTargetable(0)
Phasers.SetPrimary(1)
Phasers.SetPosition(0.000000, 0.000000, 0.000000)
Phasers.SetPosition2D(64.0, 64.0)
Phasers.SetRepairComplexity(3.0)
Phasers.SetDisabledPercentage(0.5)
Phasers.SetRadius(0.002500)
Phasers.SetNormalPowerPerSecond(233.0)
Phasers.SetWeaponSystemType(Phasers.WST_PHASER)
Phasers.SetSingleFire(1)
Phasers.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
Phasers.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(Phasers)
#################################################
Virulent = App.ShipProperty_Create("Virulent")
Virulent.SetGenus(1)
Virulent.SetSpecies(106)
Virulent.SetMass(9.0)
Virulent.SetRotationalInertia(4251.0)
Virulent.SetShipName("FTB_Virulent")
Virulent.SetModelFilename("Custom/FTB/Ships/FTBVirulent/FTB_Virulent.nif")
Virulent.SetDamageResolution(6.000000)
Virulent.SetAffiliation(0)
Virulent.SetStationary(0)
Virulent.SetAIString("FedAttack")
Virulent.SetDeathExplosionSound("g_lsDeathExplosions")
App.g_kModelPropertyManager.RegisterLocalTemplate(Virulent)
#################################################
RepairSystem = App.RepairSubsystemProperty_Create("Repair System")
RepairSystem.SetMaxCondition(1276.0)
RepairSystem.SetCritical(0)
RepairSystem.SetTargetable(1)
RepairSystem.SetPrimary(1)
RepairSystem.SetPosition(0.000000, -0.140770, 0.087526)
RepairSystem.SetPosition2D(64.0, 61.9086016202)
RepairSystem.SetRepairComplexity(2.0)
RepairSystem.SetDisabledPercentage(0.5)
RepairSystem.SetRadius(0.030000)
RepairSystem.SetNormalPowerPerSecond(1.0)
RepairSystem.SetMaxRepairPoints(0.53)
RepairSystem.SetNumRepairTeams(1)
App.g_kModelPropertyManager.RegisterLocalTemplate(RepairSystem)
#################################################
SensorArray = App.SensorProperty_Create("Sensor Array")
SensorArray.SetMaxCondition(1911.0)
SensorArray.SetCritical(0)
SensorArray.SetTargetable(0)
SensorArray.SetPrimary(1)
SensorArray.SetPosition(0.000000, 0.424072, 0.017209)
SensorArray.SetPosition2D(64.0, 66.255706907)
SensorArray.SetRepairComplexity(0.5)
SensorArray.SetDisabledPercentage(0.4)
SensorArray.SetRadius(0.020000)
SensorArray.SetNormalPowerPerSecond(1200.0)
SensorArray.SetBaseSensorRange(3000.0)
SensorArray.SetMaxProbes(4)
App.g_kModelPropertyManager.RegisterLocalTemplate(SensorArray)
#################################################
WarpEngines = App.WarpEngineProperty_Create("Warp Engines")
WarpEngines.SetMaxCondition(1247.0)
WarpEngines.SetCritical(0)
WarpEngines.SetTargetable(0)
WarpEngines.SetPrimary(1)
WarpEngines.SetPosition(0.000000, 0.000000, -0.020000)
WarpEngines.SetPosition2D(64.0, 64.0841551611)
WarpEngines.SetRepairComplexity(3.0)
WarpEngines.SetDisabledPercentage(0.5)
WarpEngines.SetRadius(0.010000)
WarpEngines.SetNormalPowerPerSecond(0.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpEngines)
#################################################
Torpedoes = App.TorpedoSystemProperty_Create("Torpedoes")
Torpedoes.SetMaxCondition(1235.0)
Torpedoes.SetCritical(0)
Torpedoes.SetTargetable(0)
Torpedoes.SetPrimary(1)
Torpedoes.SetPosition(0.000000, 0.000000, 0.000000)
Torpedoes.SetPosition2D(64.0, 64.0)
Torpedoes.SetRepairComplexity(3.0)
Torpedoes.SetDisabledPercentage(0.5)
Torpedoes.SetRadius(0.002)
Torpedoes.SetNormalPowerPerSecond(233.0)
Torpedoes.SetWeaponSystemType(Torpedoes.WST_TORPEDO)
Torpedoes.SetSingleFire(0)
Torpedoes.SetAimedWeapon(1)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
Torpedoes.SetFiringChainString(kFiringChainString)
Torpedoes.SetMaxTorpedoes(0, 8)
Torpedoes.SetTorpedoScript(0, "ftb.Projectiles.FTBDomMine")
Torpedoes.SetNumAmmoTypes(1)
App.g_kModelPropertyManager.RegisterLocalTemplate(Torpedoes)
def LoadPropertySet(pObj):


	"Sets up the object's properties."
	prop = App.g_kModelPropertyManager.FindByName("Hull", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse Engines", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp Core", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Sensor Array", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Shield Generator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Phasers", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Virulent", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Repair System", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp Engines", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Port Warp", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Star Warp", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenForward", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenBack", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenLeft", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenRight", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenUp", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenDown", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("FirstPersonCamera", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Torpedoes", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Star Beam", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Port Beam", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Probe Launcher", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Mine Replicator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Mine Launcher", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
