# D:\Games\FTB\scripts\ships\Hardpoints\ftb_nor.py
# This file was automatically generated - modify at your own risk.
#

import App
import GlobalPropertyTemplates
# Setting up local templates.
#################################################
PortImpulse = App.EngineProperty_Create("Port Impulse")
PortImpulse.SetMaxCondition(10080.0)
PortImpulse.SetCritical(0)
PortImpulse.SetTargetable(1)
PortImpulse.SetPrimary(1)
PortImpulse.SetPosition(-0.643628, 0.364137, -0.014969)
PortImpulse.SetPosition2D(27.4009844514, 63.906387433)
PortImpulse.SetRepairComplexity(3.0)
PortImpulse.SetDisabledPercentage(0.5)
PortImpulse.SetRadius(0.200000)
PortImpulse.SetEngineType(PortImpulse.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(PortImpulse)
#################################################
StarImpulse = App.EngineProperty_Create("Star Impulse")
StarImpulse.SetMaxCondition(10080.0)
StarImpulse.SetCritical(0)
StarImpulse.SetTargetable(1)
StarImpulse.SetPrimary(1)
StarImpulse.SetPosition(0.639177, 0.364137, -0.012169)
StarImpulse.SetPosition2D(100.345915593, 63.9234762048)
StarImpulse.SetRepairComplexity(3.0)
StarImpulse.SetDisabledPercentage(0.5)
StarImpulse.SetRadius(0.200000)
StarImpulse.SetEngineType(StarImpulse.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(StarImpulse)
#################################################
WarpEngine1 = App.EngineProperty_Create("Warp Engine 1")
WarpEngine1.SetMaxCondition(9506.0)
WarpEngine1.SetCritical(0)
WarpEngine1.SetTargetable(1)
WarpEngine1.SetPrimary(1)
WarpEngine1.SetPosition(-0.411947, 0.639696, 0.112227)
WarpEngine1.SetPosition2D(40.5752039094, 65.4253875818)
WarpEngine1.SetRepairComplexity(3.0)
WarpEngine1.SetDisabledPercentage(0.5)
WarpEngine1.SetRadius(0.150000)
WarpEngine1.SetEngineType(WarpEngine1.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpEngine1)
#################################################
ImpulseEngines = App.ImpulseEngineProperty_Create("Impulse Engines")
ImpulseEngines.SetMaxCondition(8753.0)
ImpulseEngines.SetCritical(0)
ImpulseEngines.SetTargetable(0)
ImpulseEngines.SetPrimary(1)
ImpulseEngines.SetPosition(0.400000, 0.700000, 0.020000)
ImpulseEngines.SetPosition2D(86.7454464682, 64.2525138637)
ImpulseEngines.SetRepairComplexity(3.0)
ImpulseEngines.SetDisabledPercentage(0.5)
ImpulseEngines.SetRadius(0.080000)
ImpulseEngines.SetNormalPowerPerSecond(1691.37073171)
ImpulseEngines.SetMaxAccel(0.67575)
ImpulseEngines.SetMaxAngularAccel(0.0001)
ImpulseEngines.SetMaxAngularVelocity(0.00025)
ImpulseEngines.SetMaxSpeed(3.0)
ImpulseEngines.SetEngineSound('Cardassian Engines')
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngines)
#################################################
PortSpiralWave = App.PhaserProperty_Create("Port Spiral Wave")
PortSpiralWave.SetMaxCondition(8962.0)
PortSpiralWave.SetCritical(0)
PortSpiralWave.SetTargetable(1)
PortSpiralWave.SetPrimary(1)
PortSpiralWave.SetPosition(-0.779921, 0.561895, 0.045689)
PortSpiralWave.SetPosition2D(19.6508716126, 64.4798056942)
PortSpiralWave.SetRepairComplexity(2.4)
PortSpiralWave.SetDisabledPercentage(0.75)
PortSpiralWave.SetRadius(0.100000)
PortSpiralWave.SetDumbfire(0)
PortSpiralWave.SetWeaponID(1)
PortSpiralWave.SetGroups(1)
PortSpiralWave.SetDamageRadiusFactor(0.1)
PortSpiralWave.SetIconNum(364)
PortSpiralWave.SetIconPositionX(46)
PortSpiralWave.SetIconPositionY(38)
PortSpiralWave.SetIconAboveShip(1)
PortSpiralWave.SetFireSound('Galor Phaser')
PortSpiralWave.SetMaxCharge(3.5)
PortSpiralWave.SetMaxDamage(4000.0)
PortSpiralWave.SetMaxDamageDistance(50.0)
PortSpiralWave.SetMinFiringCharge(2.0)
PortSpiralWave.SetNormalDischargeRate(1.0)
PortSpiralWave.SetRechargeRate(0.366)
PortSpiralWave.SetIndicatorIconNum(510)
PortSpiralWave.SetIndicatorIconPositionX(39)
PortSpiralWave.SetIndicatorIconPositionY(48)
PortSpiralWaveForward = App.TGPoint3()
PortSpiralWaveForward.SetXYZ(-0.550774, 0.828201, 0.103590)
PortSpiralWaveUp = App.TGPoint3()
PortSpiralWaveUp.SetXYZ(0.031027, -0.102989, 0.994198)
PortSpiralWave.SetOrientation(PortSpiralWaveForward, PortSpiralWaveUp)
PortSpiralWave.SetWidth(0.001000)
PortSpiralWave.SetLength(0.001000)
PortSpiralWave.SetArcWidthAngles(-0.959931, 0.698132)
PortSpiralWave.SetArcHeightAngles(-0.785398, 0.785398)
PortSpiralWave.SetPhaserTextureStart(1)
PortSpiralWave.SetPhaserTextureEnd(15)
PortSpiralWave.SetPhaserWidth(0.5)
PortSpiralWave.SetNumSides(6)
PortSpiralWave.SetMainRadius(0.1)
PortSpiralWave.SetTaperRadius(0.02)
PortSpiralWave.SetCoreScale(0.6)
PortSpiralWave.SetTaperRatio(0.25)
PortSpiralWave.SetTaperMinLength(5.0)
PortSpiralWave.SetTaperMaxLength(30.0)
PortSpiralWave.SetLengthTextureTilePerUnit(0.1)
PortSpiralWave.SetPerimeterTile(1.0)
PortSpiralWave.SetTextureSpeed(2.5)
PortSpiralWave.SetTextureName('Custom/FTB/textures/Tactical/Laurelin_CardBeam03.tga')
kColor = App.TGColorA()
kColor.SetRGBA(0.721569, 0.556863, 0.000000, 1.000000)
PortSpiralWave.SetOuterShellColor(kColor)
kColor.SetRGBA(0.721569, 0.556863, 0.000000, 1.000000)
PortSpiralWave.SetInnerShellColor(kColor)
kColor.SetRGBA(0.984314, 0.756863, 0.058824, 1.000000)
PortSpiralWave.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.000000, 1.000000, 1.000000, 1.000000)
PortSpiralWave.SetInnerCoreColor(kColor)
App.g_kModelPropertyManager.RegisterLocalTemplate(PortSpiralWave)
#################################################
StarSpiralWave = App.PhaserProperty_Create("Star Spiral Wave")
StarSpiralWave.SetMaxCondition(8962.0)
StarSpiralWave.SetCritical(0)
StarSpiralWave.SetTargetable(1)
StarSpiralWave.SetPrimary(1)
StarSpiralWave.SetPosition(0.758357, 0.562107, 0.046287)
StarSpiralWave.SetPosition2D(107.122921368, 64.486601769)
StarSpiralWave.SetRepairComplexity(2.4)
StarSpiralWave.SetDisabledPercentage(0.75)
StarSpiralWave.SetRadius(0.100000)
StarSpiralWave.SetDumbfire(0)
StarSpiralWave.SetWeaponID(1)
StarSpiralWave.SetGroups(1)
StarSpiralWave.SetDamageRadiusFactor(0.1)
StarSpiralWave.SetIconNum(364)
StarSpiralWave.SetIconPositionX(87)
StarSpiralWave.SetIconPositionY(38)
StarSpiralWave.SetIconAboveShip(1)
StarSpiralWave.SetFireSound('Galor Phaser')
StarSpiralWave.SetMaxCharge(3.5)
StarSpiralWave.SetMaxDamage(4000.0)
StarSpiralWave.SetMaxDamageDistance(50.0)
StarSpiralWave.SetMinFiringCharge(2.0)
StarSpiralWave.SetNormalDischargeRate(1.0)
StarSpiralWave.SetRechargeRate(0.366)
StarSpiralWave.SetIndicatorIconNum(510)
StarSpiralWave.SetIndicatorIconPositionX(80)
StarSpiralWave.SetIndicatorIconPositionY(48)
StarSpiralWaveForward = App.TGPoint3()
StarSpiralWaveForward.SetXYZ(0.550774, 0.828201, 0.103590)
StarSpiralWaveUp = App.TGPoint3()
StarSpiralWaveUp.SetXYZ(-0.031208, -0.103590, 0.994130)
StarSpiralWave.SetOrientation(StarSpiralWaveForward, StarSpiralWaveUp)
StarSpiralWave.SetWidth(0.001000)
StarSpiralWave.SetLength(0.001000)
StarSpiralWave.SetArcWidthAngles(-0.698132, 0.959931)
StarSpiralWave.SetArcHeightAngles(-0.785398, 0.785398)
StarSpiralWave.SetPhaserTextureStart(1)
StarSpiralWave.SetPhaserTextureEnd(15)
StarSpiralWave.SetPhaserWidth(0.5)
StarSpiralWave.SetNumSides(6)
StarSpiralWave.SetMainRadius(0.1)
StarSpiralWave.SetTaperRadius(0.02)
StarSpiralWave.SetCoreScale(0.6)
StarSpiralWave.SetTaperRatio(0.25)
StarSpiralWave.SetTaperMinLength(5.0)
StarSpiralWave.SetTaperMaxLength(30.0)
StarSpiralWave.SetLengthTextureTilePerUnit(0.1)
StarSpiralWave.SetPerimeterTile(1.0)
StarSpiralWave.SetTextureSpeed(2.5)
StarSpiralWave.SetTextureName('Custom/FTB/textures/Tactical/Laurelin_CardBeam03.tga')
kColor = App.TGColorA()
kColor.SetRGBA(0.721569, 0.556863, 0.000000, 1.000000)
StarSpiralWave.SetOuterShellColor(kColor)
kColor.SetRGBA(0.721569, 0.556863, 0.000000, 1.000000)
StarSpiralWave.SetInnerShellColor(kColor)
kColor.SetRGBA(0.984314, 0.756863, 0.058824, 1.000000)
StarSpiralWave.SetOuterCoreColor(kColor)
kColor.SetRGBA(1.000000, 1.000000, 1.000000, 1.000000)
StarSpiralWave.SetInnerCoreColor(kColor)
App.g_kModelPropertyManager.RegisterLocalTemplate(StarSpiralWave)
#################################################
ShieldGenerator = App.ShieldProperty_Create("Shield Generator")
ShieldGenerator.SetMaxCondition(9506.0)
ShieldGenerator.SetCritical(0)
ShieldGenerator.SetTargetable(1)
ShieldGenerator.SetPrimary(1)
ShieldGenerator.SetPosition(0.000000, 0.980000, 0.150000)
ShieldGenerator.SetPosition2D(64.0, 66.8779153586)
ShieldGenerator.SetRepairComplexity(2.0)
ShieldGenerator.SetDisabledPercentage(0.5)
ShieldGenerator.SetRadius(0.150000)
ShieldGenerator.SetNormalPowerPerSecond(80000.0)
ShieldGeneratorShieldGlowColor = App.TGColorA()
ShieldGeneratorShieldGlowColor.SetRGBA(1.000000, 0.647059, 0.192157, 0.466667)
ShieldGenerator.SetShieldGlowColor(ShieldGeneratorShieldGlowColor)
ShieldGenerator.SetShieldGlowDecay(0.1)
ShieldGenerator.SetMaxShields(ShieldGenerator.FRONT_SHIELDS, 400000.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.REAR_SHIELDS, 400000.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.TOP_SHIELDS, 400000.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.BOTTOM_SHIELDS, 400000.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.LEFT_SHIELDS, 400000.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.RIGHT_SHIELDS, 400000.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.FRONT_SHIELDS, 817.87012987)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.REAR_SHIELDS, 817.87012987)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.TOP_SHIELDS, 817.87012987)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.BOTTOM_SHIELDS, 817.87012987)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.LEFT_SHIELDS, 817.87012987)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.RIGHT_SHIELDS, 817.87012987)
App.g_kModelPropertyManager.RegisterLocalTemplate(ShieldGenerator)
#################################################
WarpCore = App.PowerProperty_Create("Warp Core")
WarpCore.SetMaxCondition(13932.0)
WarpCore.SetCritical(1)
WarpCore.SetTargetable(1)
WarpCore.SetPrimary(1)
WarpCore.SetPosition(-0.040000, 0.300000, -0.180000)
WarpCore.SetPosition2D(61.7254553532, 63.446167072)
WarpCore.SetRepairComplexity(2.0)
WarpCore.SetDisabledPercentage(0.5)
WarpCore.SetRadius(0.170000)
WarpCore.SetMainBatteryLimit(16550000.0)
WarpCore.SetBackupBatteryLimit(5296000.0)
WarpCore.SetMainConduitCapacity(79440.0)
WarpCore.SetBackupConduitCapacity(26480.0)
WarpCore.SetPowerOutput(66200.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpCore)
#################################################
Hull = App.HullProperty_Create("Hull")
Hull.SetMaxCondition(24537.0)
Hull.SetCritical(1)
Hull.SetTargetable(1)
Hull.SetPrimary(1)
Hull.SetPosition(0.000000, 0.880000, -0.100000)
Hull.SetPosition2D(64.0, 62.5676734621)
Hull.SetRepairComplexity(3.0)
Hull.SetDisabledPercentage(0.0)
Hull.SetRadius(0.500000)
App.g_kModelPropertyManager.RegisterLocalTemplate(Hull)
#################################################
ForwardTorpedo1 = App.TorpedoTubeProperty_Create("Forward Torpedo 1")
ForwardTorpedo1.SetMaxCondition(8448.0)
ForwardTorpedo1.SetCritical(0)
ForwardTorpedo1.SetTargetable(1)
ForwardTorpedo1.SetPrimary(1)
ForwardTorpedo1.SetPosition(-0.163392, 0.782165, -0.050292)
ForwardTorpedo1.SetPosition2D(54.7089400267, 63.3357162614)
ForwardTorpedo1.SetRepairComplexity(4.0)
ForwardTorpedo1.SetDisabledPercentage(0.75)
ForwardTorpedo1.SetRadius(0.050000)
ForwardTorpedo1.SetDumbfire(1)
ForwardTorpedo1.SetWeaponID(0)
ForwardTorpedo1.SetGroups(2)
ForwardTorpedo1.SetDamageRadiusFactor(0.17)
ForwardTorpedo1.SetIconNum(370)
ForwardTorpedo1.SetIconPositionX(72)
ForwardTorpedo1.SetIconPositionY(36)
ForwardTorpedo1.SetIconAboveShip(0)
ForwardTorpedo1.SetImmediateDelay(0.25)
ForwardTorpedo1.SetReloadDelay(30.0)
ForwardTorpedo1.SetMaxReady(1)
ForwardTorpedo1Direction = App.TGPoint3()
ForwardTorpedo1Direction.SetXYZ(0.000000, 0.997754, -0.066981)
ForwardTorpedo1.SetDirection(ForwardTorpedo1Direction)
ForwardTorpedo1Right = App.TGPoint3()
ForwardTorpedo1Right.SetXYZ(1.000000, 0.000000, 0.000000)
ForwardTorpedo1.SetRight(ForwardTorpedo1Right)
App.g_kModelPropertyManager.RegisterLocalTemplate(ForwardTorpedo1)
#################################################
ForwardTorpedo2 = App.TorpedoTubeProperty_Create("Forward Torpedo 2")
ForwardTorpedo2.SetMaxCondition(8448.0)
ForwardTorpedo2.SetCritical(0)
ForwardTorpedo2.SetTargetable(1)
ForwardTorpedo2.SetPrimary(1)
ForwardTorpedo2.SetPosition(0.141965, 0.782135, -0.050743)
ForwardTorpedo2.SetPosition2D(72.0726432697, 63.3300694047)
ForwardTorpedo2.SetRepairComplexity(4.0)
ForwardTorpedo2.SetDisabledPercentage(0.75)
ForwardTorpedo2.SetRadius(0.050000)
ForwardTorpedo2.SetDumbfire(1)
ForwardTorpedo2.SetWeaponID(0)
ForwardTorpedo2.SetGroups(2)
ForwardTorpedo2.SetDamageRadiusFactor(0.17)
ForwardTorpedo2.SetIconNum(370)
ForwardTorpedo2.SetIconPositionX(82)
ForwardTorpedo2.SetIconPositionY(36)
ForwardTorpedo2.SetIconAboveShip(0)
ForwardTorpedo2.SetImmediateDelay(0.25)
ForwardTorpedo2.SetReloadDelay(30.0)
ForwardTorpedo2.SetMaxReady(1)
ForwardTorpedo2Direction = App.TGPoint3()
ForwardTorpedo2Direction.SetXYZ(0.000000, 0.997754, -0.066981)
ForwardTorpedo2.SetDirection(ForwardTorpedo2Direction)
ForwardTorpedo2Right = App.TGPoint3()
ForwardTorpedo2Right.SetXYZ(1.000000, 0.000000, 0.000000)
ForwardTorpedo2.SetRight(ForwardTorpedo2Right)
App.g_kModelPropertyManager.RegisterLocalTemplate(ForwardTorpedo2)
#################################################
ViewscreenForward = App.PositionOrientationProperty_Create("ViewscreenForward")

ViewscreenForwardForward = App.TGPoint3()
ViewscreenForwardForward.SetXYZ(0.000000, 1.000000, 0.000000)
ViewscreenForwardUp = App.TGPoint3()
ViewscreenForwardUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenForwardRight = App.TGPoint3()
ViewscreenForwardRight.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenForward.SetOrientation(ViewscreenForwardForward, ViewscreenForwardUp, ViewscreenForwardRight)
ViewscreenForwardPosition = App.TGPoint3()
ViewscreenForwardPosition.SetXYZ(0.000000, 1.880000, 0.190000)
ViewscreenForward.SetPosition(ViewscreenForwardPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenForward)
#################################################
ViewscreenBack = App.PositionOrientationProperty_Create("ViewscreenBack")

ViewscreenBackForward = App.TGPoint3()
ViewscreenBackForward.SetXYZ(0.000000, -1.000000, 0.000000)
ViewscreenBackUp = App.TGPoint3()
ViewscreenBackUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenBackRight = App.TGPoint3()
ViewscreenBackRight.SetXYZ(-1.000000, 0.000000, 0.000000)
ViewscreenBack.SetOrientation(ViewscreenBackForward, ViewscreenBackUp, ViewscreenBackRight)
ViewscreenBackPosition = App.TGPoint3()
ViewscreenBackPosition.SetXYZ(0.000000, -1.120000, 0.000000)
ViewscreenBack.SetPosition(ViewscreenBackPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenBack)
#################################################
ViewscreenLeft = App.PositionOrientationProperty_Create("ViewscreenLeft")

ViewscreenLeftForward = App.TGPoint3()
ViewscreenLeftForward.SetXYZ(-1.000000, 0.000000, 0.000000)
ViewscreenLeftUp = App.TGPoint3()
ViewscreenLeftUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenLeftRight = App.TGPoint3()
ViewscreenLeftRight.SetXYZ(0.000000, 1.000000, 0.000000)
ViewscreenLeft.SetOrientation(ViewscreenLeftForward, ViewscreenLeftUp, ViewscreenLeftRight)
ViewscreenLeftPosition = App.TGPoint3()
ViewscreenLeftPosition.SetXYZ(0.000000, 1.880000, 0.190000)
ViewscreenLeft.SetPosition(ViewscreenLeftPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenLeft)
#################################################
ViewscreenRight = App.PositionOrientationProperty_Create("ViewscreenRight")

ViewscreenRightForward = App.TGPoint3()
ViewscreenRightForward.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenRightUp = App.TGPoint3()
ViewscreenRightUp.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenRightRight = App.TGPoint3()
ViewscreenRightRight.SetXYZ(0.000000, -1.000000, 0.000000)
ViewscreenRight.SetOrientation(ViewscreenRightForward, ViewscreenRightUp, ViewscreenRightRight)
ViewscreenRightPosition = App.TGPoint3()
ViewscreenRightPosition.SetXYZ(0.000000, 1.880000, 0.190000)
ViewscreenRight.SetPosition(ViewscreenRightPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenRight)
#################################################
ViewscreenUp = App.PositionOrientationProperty_Create("ViewscreenUp")

ViewscreenUpForward = App.TGPoint3()
ViewscreenUpForward.SetXYZ(0.000000, 0.000000, 1.000000)
ViewscreenUpUp = App.TGPoint3()
ViewscreenUpUp.SetXYZ(0.000000, -1.000000, 0.000000)
ViewscreenUpRight = App.TGPoint3()
ViewscreenUpRight.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenUp.SetOrientation(ViewscreenUpForward, ViewscreenUpUp, ViewscreenUpRight)
ViewscreenUpPosition = App.TGPoint3()
ViewscreenUpPosition.SetXYZ(0.000000, 1.880000, 0.190000)
ViewscreenUp.SetPosition(ViewscreenUpPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenUp)
#################################################
ViewscreenDown = App.PositionOrientationProperty_Create("ViewscreenDown")

ViewscreenDownForward = App.TGPoint3()
ViewscreenDownForward.SetXYZ(0.000000, 0.000000, -1.000000)
ViewscreenDownUp = App.TGPoint3()
ViewscreenDownUp.SetXYZ(0.000000, 1.000000, 0.000000)
ViewscreenDownRight = App.TGPoint3()
ViewscreenDownRight.SetXYZ(1.000000, 0.000000, 0.000000)
ViewscreenDown.SetOrientation(ViewscreenDownForward, ViewscreenDownUp, ViewscreenDownRight)
ViewscreenDownPosition = App.TGPoint3()
ViewscreenDownPosition.SetXYZ(0.000000, 1.880000, 0.070000)
ViewscreenDown.SetPosition(ViewscreenDownPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(ViewscreenDown)
#################################################
FirstPersonCamera = App.PositionOrientationProperty_Create("FirstPersonCamera")

FirstPersonCameraForward = App.TGPoint3()
FirstPersonCameraForward.SetXYZ(0.000000, 1.000000, 0.000000)
FirstPersonCameraUp = App.TGPoint3()
FirstPersonCameraUp.SetXYZ(0.000000, 0.000000, 1.000000)
FirstPersonCameraRight = App.TGPoint3()
FirstPersonCameraRight.SetXYZ(1.000000, 0.000000, 0.000000)
FirstPersonCamera.SetOrientation(FirstPersonCameraForward, FirstPersonCameraUp, FirstPersonCameraRight)
FirstPersonCameraPosition = App.TGPoint3()
FirstPersonCameraPosition.SetXYZ(0.000000, 1.880000, 0.190000)
FirstPersonCamera.SetPosition(FirstPersonCameraPosition)
App.g_kModelPropertyManager.RegisterLocalTemplate(FirstPersonCamera)
#################################################
Compressors = App.WeaponSystemProperty_Create("Compressors")
Compressors.SetMaxCondition(8962.0)
Compressors.SetCritical(0)
Compressors.SetTargetable(0)
Compressors.SetPrimary(1)
Compressors.SetPosition(0.000000, 0.880000, 0.000000)
Compressors.SetPosition2D(64.0, 64.0)
Compressors.SetRepairComplexity(3.0)
Compressors.SetDisabledPercentage(0.5)
Compressors.SetRadius(0.100000)
Compressors.SetNormalPowerPerSecond(9359.0)
Compressors.SetWeaponSystemType(Compressors.WST_PHASER)
Compressors.SetSingleFire(1)
Compressors.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
Compressors.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(Compressors)
#################################################
Bakrus = App.ShipProperty_Create("Bakrus")
Bakrus.SetGenus(1)
Bakrus.SetSpecies(201)
Bakrus.SetMass(440.0)
Bakrus.SetRotationalInertia(225001.0)
Bakrus.SetShipName("FTB_Bakrus")
Bakrus.SetModelFilename("Custom/FTB/Ships/FTBBakrus/FTB_Bakrus.nif")
Bakrus.SetDamageResolution(10.000000)
Bakrus.SetAffiliation(0)
Bakrus.SetStationary(0)
Bakrus.SetAIString("NonFedAttack")
Bakrus.SetDeathExplosionSound("g_lsDeathExplosions")
App.g_kModelPropertyManager.RegisterLocalTemplate(Bakrus)
#################################################
RepairSubsystem = App.RepairSubsystemProperty_Create("Repair Subsystem")
RepairSubsystem.SetMaxCondition(8962.0)
RepairSubsystem.SetCritical(0)
RepairSubsystem.SetTargetable(1)
RepairSubsystem.SetPrimary(1)
RepairSubsystem.SetPosition(0.000000, -0.723000, 0.027000)
RepairSubsystem.SetPosition2D(64.0, 63.6638329615)
RepairSubsystem.SetRepairComplexity(2.0)
RepairSubsystem.SetDisabledPercentage(0.5)
RepairSubsystem.SetRadius(0.100000)
RepairSubsystem.SetNormalPowerPerSecond(1.0)
RepairSubsystem.SetMaxRepairPoints(184.39)
RepairSubsystem.SetNumRepairTeams(2)
App.g_kModelPropertyManager.RegisterLocalTemplate(RepairSubsystem)
#################################################
SensorArray = App.SensorProperty_Create("Sensor Array")
SensorArray.SetMaxCondition(12850.0)
SensorArray.SetCritical(0)
SensorArray.SetTargetable(0)
SensorArray.SetPrimary(1)
SensorArray.SetPosition(0.000000, 2.250000, 0.178000)
SensorArray.SetPosition2D(64.0, 71.4742476822)
SensorArray.SetRepairComplexity(0.5)
SensorArray.SetDisabledPercentage(0.4)
SensorArray.SetRadius(0.070000)
SensorArray.SetNormalPowerPerSecond(1600.0)
SensorArray.SetBaseSensorRange(6000.0)
SensorArray.SetMaxProbes(10)
App.g_kModelPropertyManager.RegisterLocalTemplate(SensorArray)
#################################################
WarpEngine = App.WarpEngineProperty_Create("Warp Engine")
WarpEngine.SetMaxCondition(9506.0)
WarpEngine.SetCritical(0)
WarpEngine.SetTargetable(0)
WarpEngine.SetPrimary(1)
WarpEngine.SetPosition(0.411947, 0.639696, 0.112227)
WarpEngine.SetPosition2D(87.4247960906, 65.4253875818)
WarpEngine.SetRepairComplexity(3.0)
WarpEngine.SetDisabledPercentage(0.5)
WarpEngine.SetRadius(0.150000)
WarpEngine.SetNormalPowerPerSecond(0.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpEngine)
#################################################
Torpedoes = App.TorpedoSystemProperty_Create("Torpedoes")
Torpedoes.SetMaxCondition(7982.0)
Torpedoes.SetCritical(0)
Torpedoes.SetTargetable(0)
Torpedoes.SetPrimary(1)
Torpedoes.SetPosition(0.000000, 0.000000, 0.000000)
Torpedoes.SetPosition2D(64.0, 64.0)
Torpedoes.SetRepairComplexity(3.0)
Torpedoes.SetDisabledPercentage(0.5)
Torpedoes.SetRadius(0.002)
Torpedoes.SetNormalPowerPerSecond(9359.0)
Torpedoes.SetWeaponSystemType(Torpedoes.WST_TORPEDO)
Torpedoes.SetSingleFire(0)
Torpedoes.SetAimedWeapon(1)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
Torpedoes.SetFiringChainString(kFiringChainString)
Torpedoes.SetMaxTorpedoes(0, 1000)
Torpedoes.SetTorpedoScript(0, "ftb.Projectiles.FTBCardTorpedo")
Torpedoes.SetMaxTorpedoes(1, 0)
Torpedoes.SetTorpedoScript(1, "ftb.Projectiles.FTBCardPlasmaBurst")
Torpedoes.SetNumAmmoTypes(2)
App.g_kModelPropertyManager.RegisterLocalTemplate(Torpedoes)
def LoadPropertySet(pObj):


	"Sets up the object's properties."
	prop = App.g_kModelPropertyManager.FindByName("Hull", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Shield Generator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp Core", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Compressors", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse Engines", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Port Impulse", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Star Impulse", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp Engine", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp Engine 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Repair Subsystem", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Sensor Array", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Bakrus", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenForward", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenBack", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenLeft", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenRight", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenUp", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("ViewscreenDown", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("FirstPersonCamera", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Port Spiral Wave", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Star Spiral Wave", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Forward Torpedo 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Forward Torpedo 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Torpedoes", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
