# C:\Utopia\Current\Build\scripts\ships\Hardpoints\kessokmine.py
# This file was automatically generated - modify at your own risk.
#

import App
import GlobalPropertyTemplates
# Setting up local templates.
#################################################
ImpulseEngine1 = App.EngineProperty_Create("Impulse Engine 1")
ImpulseEngine1.SetMaxCondition(3475.0)
ImpulseEngine1.SetCritical(0)
ImpulseEngine1.SetTargetable(1)
ImpulseEngine1.SetPrimary(1)
ImpulseEngine1.SetPosition(0.000000, -0.100000, 0.400000)
ImpulseEngine1.SetPosition2D(64.0, 70.4383169278)
ImpulseEngine1.SetRepairComplexity(3.0)
ImpulseEngine1.SetDisabledPercentage(0.5)
ImpulseEngine1.SetRadius(0.170000)
ImpulseEngine1.SetEngineType(ImpulseEngine1.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngine1)
#################################################
ImpulseEngine2 = App.EngineProperty_Create("Impulse Engine 2")
ImpulseEngine2.SetMaxCondition(3475.0)
ImpulseEngine2.SetCritical(0)
ImpulseEngine2.SetTargetable(1)
ImpulseEngine2.SetPrimary(1)
ImpulseEngine2.SetPosition(0.320000, -0.100000, -0.200000)
ImpulseEngine2.SetPosition2D(104.919080919, 68.2922112852)
ImpulseEngine2.SetRepairComplexity(3.0)
ImpulseEngine2.SetDisabledPercentage(0.5)
ImpulseEngine2.SetRadius(0.170000)
ImpulseEngine2.SetEngineType(ImpulseEngine2.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngine2)
#################################################
ImpulseEngine3 = App.EngineProperty_Create("Impulse Engine 3")
ImpulseEngine3.SetMaxCondition(3475.0)
ImpulseEngine3.SetCritical(0)
ImpulseEngine3.SetTargetable(1)
ImpulseEngine3.SetPrimary(1)
ImpulseEngine3.SetPosition(-0.320000, -0.100000, -0.200000)
ImpulseEngine3.SetPosition2D(23.0809190809, 68.2922112852)
ImpulseEngine3.SetRepairComplexity(3.0)
ImpulseEngine3.SetDisabledPercentage(0.5)
ImpulseEngine3.SetRadius(0.170000)
ImpulseEngine3.SetEngineType(ImpulseEngine3.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngine3)
# Property load function.
ImpulseEngines = App.ImpulseEngineProperty_Create("Impulse Engines")
ImpulseEngines.SetMaxCondition(3815.0)
ImpulseEngines.SetCritical(0)
ImpulseEngines.SetTargetable(0)
ImpulseEngines.SetPrimary(1)
ImpulseEngines.SetPosition(0.000000, 0.000000, 0.000000)
ImpulseEngines.SetPosition2D(64.0, 64.0)
ImpulseEngines.SetRepairComplexity(3.0)
ImpulseEngines.SetDisabledPercentage(0.5)
ImpulseEngines.SetRadius(0.250000)
ImpulseEngines.SetNormalPowerPerSecond(2973.77235512)
ImpulseEngines.SetMaxAccel(2.175)
ImpulseEngines.SetMaxAngularAccel(0.16)
ImpulseEngines.SetMaxAngularVelocity(0.56)
ImpulseEngines.SetMaxSpeed(2.2)
ImpulseEngines.SetEngineSound('Federation Engines')
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngines)
#################################################
ShieldGenerator = App.ShieldProperty_Create("Shield Generator")
ShieldGenerator.SetMaxCondition(3201.0)
ShieldGenerator.SetCritical(0)
ShieldGenerator.SetTargetable(1)
ShieldGenerator.SetPrimary(1)
ShieldGenerator.SetPosition(0.000000, 0.010000, 0.000000)
ShieldGenerator.SetPosition2D(64.0, 64.0)
ShieldGenerator.SetRepairComplexity(2.0)
ShieldGenerator.SetDisabledPercentage(0.5)
ShieldGenerator.SetRadius(0.100000)
ShieldGenerator.SetNormalPowerPerSecond(5.000000)
ShieldGeneratorShieldGlowColor = App.TGColorA()
ShieldGeneratorShieldGlowColor.SetRGBA(0.000000, 1.000000, 1.000000, 0.466667)
ShieldGenerator.SetShieldGlowColor(ShieldGeneratorShieldGlowColor)
ShieldGenerator.SetShieldGlowDecay(0.1)
ShieldGenerator.SetMaxShields(ShieldGenerator.FRONT_SHIELDS, 0.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.REAR_SHIELDS, 0.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.TOP_SHIELDS, 0.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.BOTTOM_SHIELDS, 0.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.LEFT_SHIELDS, 0.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.RIGHT_SHIELDS, 0.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.FRONT_SHIELDS, 0.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.REAR_SHIELDS, 0.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.TOP_SHIELDS, 0.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.BOTTOM_SHIELDS, 0.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.LEFT_SHIELDS, 0.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.RIGHT_SHIELDS, 0.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(ShieldGenerator)
#################################################
PowerPlant = App.PowerProperty_Create("Power Plant")
PowerPlant.SetMaxCondition(5100.0)
PowerPlant.SetCritical(1)
PowerPlant.SetTargetable(1)
PowerPlant.SetPrimary(1)
PowerPlant.SetPosition(0.000000, 0.400000, 0.000000)
PowerPlant.SetPosition2D(64.0, 64.0)
PowerPlant.SetRepairComplexity(2.0)
PowerPlant.SetDisabledPercentage(0.5)
PowerPlant.SetRadius(0.200000)
PowerPlant.SetMainBatteryLimit(1400000.0)
PowerPlant.SetBackupBatteryLimit(800000.0)
PowerPlant.SetMainConduitCapacity(12000.0)
PowerPlant.SetBackupConduitCapacity(4000.0)
PowerPlant.SetPowerOutput(10000.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(PowerPlant)
#################################################
CloakingDevice = App.CloakingSubsystemProperty_Create("Cloaking Device")
CloakingDevice.SetMaxCondition(3815.0)
CloakingDevice.SetCritical(0)
CloakingDevice.SetTargetable(1)
CloakingDevice.SetPrimary(1)
CloakingDevice.SetPosition(0.000000, 0.000000, 0.000000)
CloakingDevice.SetPosition2D(64.0, 64.0)
CloakingDevice.SetRepairComplexity(3.0)
CloakingDevice.SetDisabledPercentage(0.5)
CloakingDevice.SetRadius(0.250000)
CloakingDevice.SetNormalPowerPerSecond(50.000000)
CloakingDevice.SetCloakStrength(90.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(CloakingDevice)
#################################################
Hull = App.HullProperty_Create("Hull")
Hull.SetMaxCondition(8684.0)
Hull.SetCritical(1)
Hull.SetTargetable(1)
Hull.SetPrimary(1)
Hull.SetPosition(0.000000, 0.000000, 0.000000)
Hull.SetPosition2D(64.0, 64.0)
Hull.SetRepairComplexity(3.0)
Hull.SetDisabledPercentage(0.0)
Hull.SetRadius(0.220000)
App.g_kModelPropertyManager.RegisterLocalTemplate(Hull)
#################################################
TorpedoTube = App.TorpedoTubeProperty_Create("Torpedo Tube")
TorpedoTube.SetMaxCondition(3395.0)
TorpedoTube.SetCritical(0)
TorpedoTube.SetTargetable(1)
TorpedoTube.SetPrimary(1)
TorpedoTube.SetPosition(0.000000, 1.000000, 0.000000)
TorpedoTube.SetPosition2D(64.0, 64.0)
TorpedoTube.SetRepairComplexity(4.0)
TorpedoTube.SetDisabledPercentage(0.75)
TorpedoTube.SetRadius(0.150000)
TorpedoTube.SetDumbfire(1)
TorpedoTube.SetWeaponID(0)
TorpedoTube.SetGroups(0)
TorpedoTube.SetDamageRadiusFactor(0.17)
TorpedoTube.SetIconNum(270)
TorpedoTube.SetIconPositionX(80)
TorpedoTube.SetIconPositionY(21)
TorpedoTube.SetIconAboveShip(0)
TorpedoTube.SetImmediateDelay(0.25)
TorpedoTube.SetReloadDelay(36.0)
TorpedoTube.SetMaxReady(2)
TorpedoTubeDirection = App.TGPoint3()
TorpedoTubeDirection.SetXYZ(0.000000, 1.000000, 0.000000)
TorpedoTube.SetDirection(TorpedoTubeDirection)
TorpedoTubeRight = App.TGPoint3()
TorpedoTubeRight.SetXYZ(1.000000, 0.000000, 0.000000)
TorpedoTube.SetRight(TorpedoTubeRight)
App.g_kModelPropertyManager.RegisterLocalTemplate(TorpedoTube)
#################################################
KessokMine = App.ShipProperty_Create("Kessok Mine")
KessokMine.SetGenus(1)
KessokMine.SetSpecies(503)
KessokMine.SetMass(300.0)
KessokMine.SetRotationalInertia(153444.0)
KessokMine.SetShipName("Kessok Mine")
KessokMine.SetModelFilename("")
KessokMine.SetDamageResolution(2.000000)
KessokMine.SetAffiliation(0)
KessokMine.SetStationary(0)
KessokMine.SetAIString("NonFedAttack")
KessokMine.SetDeathExplosionSound("g_lsDeathExplosions")
App.g_kModelPropertyManager.RegisterLocalTemplate(KessokMine)
#################################################
SensorArray = App.SensorProperty_Create("Sensor Array")
SensorArray.SetMaxCondition(5100.0)
SensorArray.SetCritical(0)
SensorArray.SetTargetable(0)
SensorArray.SetPrimary(1)
SensorArray.SetPosition(0.000000, 0.500000, 0.350000)
SensorArray.SetPosition2D(64.0, 87.3165435963)
SensorArray.SetRepairComplexity(0.5)
SensorArray.SetDisabledPercentage(0.4)
SensorArray.SetRadius(0.200000)
SensorArray.SetNormalPowerPerSecond(1440.0)
SensorArray.SetBaseSensorRange(4800.0)
SensorArray.SetMaxProbes(10)
App.g_kModelPropertyManager.RegisterLocalTemplate(SensorArray)
#################################################
Torpedoes = App.TorpedoSystemProperty_Create("Torpedoes")
Torpedoes.SetMaxCondition(2850.0)
Torpedoes.SetCritical(0)
Torpedoes.SetTargetable(0)
Torpedoes.SetPrimary(1)
Torpedoes.SetPosition(0.000000, 0.000000, 0.000000)
Torpedoes.SetPosition2D(64.0, 64.0)
Torpedoes.SetRepairComplexity(3.0)
Torpedoes.SetDisabledPercentage(0.5)
Torpedoes.SetRadius(0.002)
Torpedoes.SetNormalPowerPerSecond(4100.0)
Torpedoes.SetWeaponSystemType(Torpedoes.WST_TORPEDO)
Torpedoes.SetSingleFire(0)
Torpedoes.SetAimedWeapon(1)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
Torpedoes.SetFiringChainString(kFiringChainString)
Torpedoes.SetMaxTorpedoes(0, 100)
Torpedoes.SetTorpedoScript(0, "ftb.Projectiles.FTBKessokTorpedo")
Torpedoes.SetMaxTorpedoes(1, 0)
Torpedoes.SetTorpedoScript(1, "ftb.Projectiles.FTBKessokPlasmaBurst")
Torpedoes.SetNumAmmoTypes(2)
App.g_kModelPropertyManager.RegisterLocalTemplate(Torpedoes)
def LoadPropertySet(pObj):


	"Sets up the object's properties."
	prop = App.g_kModelPropertyManager.FindByName("Hull", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Power Plant", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Shield Generator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Sensor Array", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Kessok Mine", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Torpedoes", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Torpedo Tube", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Cloaking Device", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse Engines", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse Engine 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse Engine 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse Engine 3", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
