# C:\Utopia\Current\Build\scripts\ships\Hardpoints\sunbuster.py
# This file was automatically generated - modify at your own risk.
#

import App
import GlobalPropertyTemplates
# Setting up local templates.
#################################################
Impulse1 = App.EngineProperty_Create("Impulse 1")
Impulse1.SetMaxCondition(9900.0)
Impulse1.SetCritical(0)
Impulse1.SetTargetable(1)
Impulse1.SetPrimary(1)
Impulse1.SetPosition(3.500000, -0.200000, -1.700000)
Impulse1.SetPosition2D(170.641275887, 75.9968262281)
Impulse1.SetRepairComplexity(3.0)
Impulse1.SetDisabledPercentage(0.5)
Impulse1.SetRadius(1.200000)
Impulse1.SetEngineType(Impulse1.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(Impulse1)
#################################################
Impulse2 = App.EngineProperty_Create("Impulse 2")
Impulse2.SetMaxCondition(9900.0)
Impulse2.SetCritical(0)
Impulse2.SetTargetable(1)
Impulse2.SetPrimary(1)
Impulse2.SetPosition(-3.500000, -0.200000, -1.700000)
Impulse2.SetPosition2D(-42.6412758867, 75.9968262281)
Impulse2.SetRepairComplexity(3.0)
Impulse2.SetDisabledPercentage(0.5)
Impulse2.SetRadius(1.200000)
Impulse2.SetEngineType(Impulse2.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(Impulse2)
#################################################
Impulse3 = App.EngineProperty_Create("Impulse 3")
Impulse3.SetMaxCondition(9900.0)
Impulse3.SetCritical(0)
Impulse3.SetTargetable(1)
Impulse3.SetPrimary(1)
Impulse3.SetPosition(0.000000, -0.200000, 4.200000)
Impulse3.SetPosition2D(64.0, 122.425508351)
Impulse3.SetRepairComplexity(3.0)
Impulse3.SetDisabledPercentage(0.5)
Impulse3.SetRadius(1.200000)
Impulse3.SetEngineType(Impulse3.EP_IMPULSE)
App.g_kModelPropertyManager.RegisterLocalTemplate(Impulse3)
#################################################
Warp1 = App.EngineProperty_Create("Warp 1")
Warp1.SetMaxCondition(19161.0)
Warp1.SetCritical(0)
Warp1.SetTargetable(1)
Warp1.SetPrimary(1)
Warp1.SetPosition(2.000000, -3.300000, -1.000000)
Warp1.SetPosition2D(124.937871935, 84.3077887906)
Warp1.SetRepairComplexity(3.0)
Warp1.SetDisabledPercentage(0.5)
Warp1.SetRadius(2.100000)
Warp1.SetEngineType(Warp1.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(Warp1)
#################################################
Warp2 = App.EngineProperty_Create("Warp 2")
Warp2.SetMaxCondition(19161.0)
Warp2.SetCritical(0)
Warp2.SetTargetable(1)
Warp2.SetPrimary(1)
Warp2.SetPosition(-2.000000, -3.300000, -1.000000)
Warp2.SetPosition2D(3.06212806475, 84.3077887906)
Warp2.SetRepairComplexity(3.0)
Warp2.SetDisabledPercentage(0.5)
Warp2.SetRadius(2.100000)
Warp2.SetEngineType(Warp2.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(Warp2)
#################################################
Warp3 = App.EngineProperty_Create("Warp 3")
Warp3.SetMaxCondition(19161.0)
Warp3.SetCritical(0)
Warp3.SetTargetable(1)
Warp3.SetPrimary(1)
Warp3.SetPosition(0.000000, -3.300000, 2.500000)
Warp3.SetPosition2D(64.0, 44.3268296091)
Warp3.SetRepairComplexity(3.0)
Warp3.SetDisabledPercentage(0.5)
Warp3.SetRadius(2.100000)
Warp3.SetEngineType(Warp3.EP_WARP)
App.g_kModelPropertyManager.RegisterLocalTemplate(Warp3)
#################################################
ImpulseEngines = App.ImpulseEngineProperty_Create("Impulse Engines")
ImpulseEngines.SetMaxCondition(3815.0)
ImpulseEngines.SetCritical(0)
ImpulseEngines.SetTargetable(0)
ImpulseEngines.SetPrimary(1)
ImpulseEngines.SetPosition(0.000000, 0.000000, 0.000000)
ImpulseEngines.SetPosition2D(64.0, 64.0)
ImpulseEngines.SetRepairComplexity(3.0)
ImpulseEngines.SetDisabledPercentage(0.5)
ImpulseEngines.SetRadius(0.250000)
ImpulseEngines.SetNormalPowerPerSecond(7966.34669268)
ImpulseEngines.SetMaxAccel(0.825)
ImpulseEngines.SetMaxAngularAccel(0.04)
ImpulseEngines.SetMaxAngularVelocity(0.1)
ImpulseEngines.SetMaxSpeed(2.2)
ImpulseEngines.SetEngineSound('Federation Engines')
App.g_kModelPropertyManager.RegisterLocalTemplate(ImpulseEngines)
#################################################
Emitter = App.PhaserProperty_Create("Emitter")
Emitter.SetMaxCondition(4277.0)
Emitter.SetCritical(0)
Emitter.SetTargetable(1)
Emitter.SetPrimary(1)
Emitter.SetPosition(0.000000, -6.700000, 0.300000)
Emitter.SetPosition2D(64.0, 54.1151838062)
Emitter.SetRepairComplexity(2.4)
Emitter.SetDisabledPercentage(0.75)
Emitter.SetRadius(0.350000)
Emitter.SetDumbfire(0)
Emitter.SetWeaponID(1)
Emitter.SetGroups(0)
Emitter.SetDamageRadiusFactor(0.1)
Emitter.SetIconNum(370)
Emitter.SetIconPositionX(77)
Emitter.SetIconPositionY(96)
Emitter.SetIconAboveShip(1)
Emitter.SetFireSound('Kessok Phaser')
Emitter.SetMaxCharge(7.0)
Emitter.SetMaxDamage(400.0)
Emitter.SetMaxDamageDistance(120.0)
Emitter.SetMinFiringCharge(4.0)
Emitter.SetNormalDischargeRate(1.0)
Emitter.SetRechargeRate(5.0)
Emitter.SetIndicatorIconNum(370)
Emitter.SetIndicatorIconPositionX(77)
Emitter.SetIndicatorIconPositionY(96)
EmitterForward = App.TGPoint3()
EmitterForward.SetXYZ(0.000000, -1.000000, 0.000000)
EmitterUp = App.TGPoint3()
EmitterUp.SetXYZ(0.000000, 0.000000, 1.000000)
Emitter.SetOrientation(EmitterForward, EmitterUp)
Emitter.SetWidth(0.100000)
Emitter.SetLength(0.100000)
Emitter.SetArcWidthAngles(-0.087266, 0.087266)
Emitter.SetArcHeightAngles(-0.087266, 0.087266)
Emitter.SetPhaserTextureStart(1)
Emitter.SetPhaserTextureEnd(15)
Emitter.SetPhaserWidth(0.5)
Emitter.SetNumSides(6)
Emitter.SetMainRadius(0.1)
Emitter.SetTaperRadius(0.02)
Emitter.SetCoreScale(0.3)
Emitter.SetTaperRatio(0.25)
Emitter.SetTaperMinLength(5.0)
Emitter.SetTaperMaxLength(30.0)
Emitter.SetLengthTextureTilePerUnit(0.1)
Emitter.SetPerimeterTile(1.0)
Emitter.SetTextureSpeed(2.5)
Emitter.SetTextureName('Custom/FTB/textures/Tactical/Laurelin_CardBeam03.tga')
kColor = App.TGColorA()
kColor.SetRGBA(0.000000, 0.501961, 0.749020, 1.000000)
Emitter.SetOuterShellColor(kColor)
kColor.SetRGBA(0.000000, 0.501961, 1.000000, 1.000000)
Emitter.SetInnerShellColor(kColor)
kColor.SetRGBA(0.501961, 1.000000, 1.000000, 1.000000)
Emitter.SetOuterCoreColor(kColor)
kColor.SetRGBA(0.000000, 1.000000, 1.000000, 1.000000)
Emitter.SetInnerCoreColor(kColor)
App.g_kModelPropertyManager.RegisterLocalTemplate(Emitter)
# Property load function.
ShieldGenerator = App.ShieldProperty_Create("Shield Generator")
ShieldGenerator.SetMaxCondition(8304.0)
ShieldGenerator.SetCritical(0)
ShieldGenerator.SetTargetable(1)
ShieldGenerator.SetPrimary(1)
ShieldGenerator.SetPosition(-1.400000, -0.420000, 1.200000)
ShieldGenerator.SetPosition2D(21.3434896453, 66.5587813876)
ShieldGenerator.SetRepairComplexity(2.0)
ShieldGenerator.SetDisabledPercentage(0.5)
ShieldGenerator.SetRadius(1.000000)
ShieldGenerator.SetNormalPowerPerSecond(8750.0)
ShieldGeneratorShieldGlowColor = App.TGColorA()
ShieldGeneratorShieldGlowColor.SetRGBA(0.294118, 0.184314, 0.811765, 0.466667)
ShieldGenerator.SetShieldGlowColor(ShieldGeneratorShieldGlowColor)
ShieldGenerator.SetShieldGlowDecay(0.1)
ShieldGenerator.SetMaxShields(ShieldGenerator.FRONT_SHIELDS, 65625.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.REAR_SHIELDS, 43750.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.TOP_SHIELDS, 52500.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.BOTTOM_SHIELDS, 52500.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.LEFT_SHIELDS, 43750.0)
ShieldGenerator.SetMaxShields(ShieldGenerator.RIGHT_SHIELDS, 43750.0)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.FRONT_SHIELDS, 36.0616994317)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.REAR_SHIELDS, 36.0616994317)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.TOP_SHIELDS, 36.0616994317)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.BOTTOM_SHIELDS, 36.0616994317)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.LEFT_SHIELDS, 36.0616994317)
ShieldGenerator.SetShieldChargePerSecond(ShieldGenerator.RIGHT_SHIELDS, 36.0616994317)
App.g_kModelPropertyManager.RegisterLocalTemplate(ShieldGenerator)
#################################################
WarpCore = App.PowerProperty_Create("Warp Core")
WarpCore.SetMaxCondition(14108.0)
WarpCore.SetCritical(1)
WarpCore.SetTargetable(1)
WarpCore.SetPrimary(1)
WarpCore.SetPosition(0.000000, -0.420000, -1.200000)
WarpCore.SetPosition2D(64.0, 71.6763441629)
WarpCore.SetRepairComplexity(2.0)
WarpCore.SetDisabledPercentage(0.5)
WarpCore.SetRadius(1.500000)
WarpCore.SetMainBatteryLimit(2478000.0)
WarpCore.SetBackupBatteryLimit(1416000.0)
WarpCore.SetMainConduitCapacity(21240.0)
WarpCore.SetBackupConduitCapacity(7080.0)
WarpCore.SetPowerOutput(17700.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpCore)
#################################################
CloakingDevice = App.CloakingSubsystemProperty_Create("Cloaking Device")
CloakingDevice.SetMaxCondition(8304.0)
CloakingDevice.SetCritical(0)
CloakingDevice.SetTargetable(1)
CloakingDevice.SetPrimary(1)
CloakingDevice.SetPosition(0.000000, 0.000000, 0.000000)
CloakingDevice.SetPosition2D(64.0, 64.0)
CloakingDevice.SetRepairComplexity(3.0)
CloakingDevice.SetDisabledPercentage(0.5)
CloakingDevice.SetRadius(1.000000)
CloakingDevice.SetNormalPowerPerSecond(10.000000)
CloakingDevice.SetCloakStrength(90.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(CloakingDevice)
#################################################
Hull = App.HullProperty_Create("Hull")
Hull.SetMaxCondition(54884.0)
Hull.SetCritical(1)
Hull.SetTargetable(1)
Hull.SetPrimary(1)
Hull.SetPosition(0.000000, 0.000000, 0.300000)
Hull.SetPosition2D(64.0, 64.3198476735)
Hull.SetRepairComplexity(3.0)
Hull.SetDisabledPercentage(0.0)
Hull.SetRadius(4.000000)
App.g_kModelPropertyManager.RegisterLocalTemplate(Hull)
#################################################
BeamEmitter = App.WeaponSystemProperty_Create("Beam Emitter")
BeamEmitter.SetMaxCondition(3815.0)
BeamEmitter.SetCritical(0)
BeamEmitter.SetTargetable(0)
BeamEmitter.SetPrimary(1)
BeamEmitter.SetPosition(0.000000, 0.000000, 0.000000)
BeamEmitter.SetPosition2D(64.0, 64.0)
BeamEmitter.SetRepairComplexity(3.0)
BeamEmitter.SetDisabledPercentage(0.5)
BeamEmitter.SetRadius(0.250000)
BeamEmitter.SetNormalPowerPerSecond(4100.0)
BeamEmitter.SetWeaponSystemType(BeamEmitter.WST_PHASER)
BeamEmitter.SetSingleFire(0)
BeamEmitter.SetAimedWeapon(0)
kFiringChainString = App.TGString()
kFiringChainString.SetString("")
BeamEmitter.SetFiringChainString(kFiringChainString)
App.g_kModelPropertyManager.RegisterLocalTemplate(BeamEmitter)
#################################################
SunBuster = App.ShipProperty_Create("Sun Buster")
SunBuster.SetGenus(1)
SunBuster.SetSpecies(713)
SunBuster.SetMass(2995.0)
SunBuster.SetRotationalInertia(1534432.0)
SunBuster.SetShipName("Device")
SunBuster.SetModelFilename("")
SunBuster.SetDamageResolution(15.000000)
SunBuster.SetAffiliation(0)
SunBuster.SetStationary(0)
SunBuster.SetAIString("NonFedAttack")
SunBuster.SetDeathExplosionSound("g_lsBigDeathExplosions")
App.g_kModelPropertyManager.RegisterLocalTemplate(SunBuster)
#################################################
RepairSystem = App.RepairSubsystemProperty_Create("Repair System")
RepairSystem.SetMaxCondition(9054.0)
RepairSystem.SetCritical(0)
RepairSystem.SetTargetable(1)
RepairSystem.SetPrimary(1)
RepairSystem.SetPosition(1.400000, -0.420000, 1.200000)
RepairSystem.SetPosition2D(106.656510355, 66.5587813876)
RepairSystem.SetRepairComplexity(2.0)
RepairSystem.SetDisabledPercentage(0.5)
RepairSystem.SetRadius(1.000000)
RepairSystem.SetNormalPowerPerSecond(1.0)
RepairSystem.SetMaxRepairPoints(748.5)
RepairSystem.SetNumRepairTeams(4)
App.g_kModelPropertyManager.RegisterLocalTemplate(RepairSystem)
#################################################
SensorArray = App.SensorProperty_Create("Sensor Array")
SensorArray.SetMaxCondition(9804.0)
SensorArray.SetCritical(0)
SensorArray.SetTargetable(0)
SensorArray.SetPrimary(1)
SensorArray.SetPosition(0.000000, 1.200000, 0.200000)
SensorArray.SetPosition2D(64.0, 65.360621849)
SensorArray.SetRepairComplexity(0.5)
SensorArray.SetDisabledPercentage(0.4)
SensorArray.SetRadius(1.000000)
SensorArray.SetNormalPowerPerSecond(1440.0)
SensorArray.SetBaseSensorRange(4800.0)
SensorArray.SetMaxProbes(10)
App.g_kModelPropertyManager.RegisterLocalTemplate(SensorArray)
#################################################
WarpEngines = App.WarpEngineProperty_Create("Warp Engines")
WarpEngines.SetMaxCondition(3815.0)
WarpEngines.SetCritical(0)
WarpEngines.SetTargetable(0)
WarpEngines.SetPrimary(1)
WarpEngines.SetPosition(0.000000, 0.000000, 0.000000)
WarpEngines.SetPosition2D(64.0, 64.0)
WarpEngines.SetRepairComplexity(3.0)
WarpEngines.SetDisabledPercentage(0.5)
WarpEngines.SetRadius(0.250000)
WarpEngines.SetNormalPowerPerSecond(0.0)
App.g_kModelPropertyManager.RegisterLocalTemplate(WarpEngines)
#################################################
def LoadPropertySet(pObj):

	"Sets up the object's properties."
	prop = App.g_kModelPropertyManager.FindByName("Hull", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp Core", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Repair System", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Shield Generator", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Sensor Array", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse Engines", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp Engines", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Sun Buster", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Impulse 3", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp 1", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp 2", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Warp 3", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Cloaking Device", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Beam Emitter", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
	prop = App.g_kModelPropertyManager.FindByName("Emitter", App.TGModelPropertyManager.LOCAL_TEMPLATES)
	if (prop != None):
		pObj.AddToSet("Scene Root", prop)
